thread = 25
timeout = 3
delay = 0.2    #设置延时，如果网速太低，增加延时，网速优可以降低延时
black = [      #禁止访问的后缀名单
    "pdf",
    "doc",
    "docx",
    "xls",
    "csv",
    "jpg",
    "png",
    "jpeg",
    "ico"
]
white = [
    "robots.txt",
    "readme.txt",
    "readme",
    "README",
    "README.txt"
]
rule = [
    '(?<=")/.*?(?=")',
    '(?<=")https?://.*?(?=")'
]

[headers]
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.44"
Accept-Language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
